keys:
  - &admin_soriphoono age1y4x8gzzcdhxvqaf9matt0eze3z3yxwx607avq4cexfkgwal4psesj39lvn
  - &admin_mrcomethru age1ntv8953h59kfumwwwytyq478937276huqwnc30n9m7h6pzy3ednq82gj0t
creation_rules:
  - path_regex: docker/.+/secrets/.*
    key_groups:
      - age:
          - *admin_soriphoono
          - *admin_mrcomethru
