services:
  backend:
    build:
      context: ../../scikidzapp/backend
      dockerfile: dockerfile
    image: scikidz-backend:latest
    environment:
      - MONGO_URI=mongodb://scikidz_service:PASSWORD@mongo:27017/scikidz?authSource=scikidz
      - MONGO_PASSWORD_FILE=/run/secrets/mongo-database-password
      - PORT=5757
    networks:
      - scikidz
      - mongo
    secrets:
      - mongo-database-password
networks:
  scikidz:
    driver: overlay
    attachable: true
  mongo:
    external: true
    name: mongodb_mongo
secrets:
  mongo-database-password:
    file: ../mongodb/secrets/mongo-database-password
