services:
  mongo:
    image: mongo:noble
    secrets:
      - mongo-root-password
      - mongo-database-password
    configs:
      - source: mongo_init
        target: /docker-entrypoint-initdb.d/init-mongo.js
        mode: 0755
    volumes:
      - mongodb-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: "admin"
      MONGO_INITDB_ROOT_PASSWORD_FILE: "/run/secrets/mongo-root-password"
      MONGO_INITDB_DATABASE: "scikidz"
      MONGO_INITDB_DATABASE_USERNAME: "scikidz_user"
      MONGO_INITDB_DATABASE_PASSWORD_FILE: "/run/secrets/mongo-database-password"
    networks:
      - mongo
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.role == manager
  mongo-express:
    image: mongo-express
    secrets:
      - mongo-database-password
      - mongo-express-password
    environment:
      ME_CONFIG_MONGODB_URL: "mongodb://scikidz_user:$$(cat /run/secrets/mongo-database-password)@mongo:27017/scikidz?authSource=scikidz"
      ME_CONFIG_BASICAUTH_ENABLED: "true"
      ME_CONFIG_BASICAUTH_USERNAME: "admin"
      ME_CONFIG_BASICAUTH_PASSWORD: "$$(cat /run/secrets/mongo-express-password)"
    networks:
      - mongo
      - proxy
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.role == manager
secrets:
  mongo-root-password:
    file: ./secrets/mongo-root-password
  mongo-database-password:
    file: ./secrets/mongo-database-password
  mongo-express-password:
    file: ./secrets/mongo-express-password
configs:
  mongo_init:
    file: ./configs/mongo-init.js
volumes:
  mongodb-data:
networks:
  mongo:
    driver: overlay
    attachable: true
  proxy:
    external: true
